version: '3'

services:
  mongodb:
    container_name: 'database-mongo'
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DATABASE_PASSWORD}
    volumes:
      - ./mongo_data:/var/lib/mongodb/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - microservices

  postgres:
    container_name: 'database-postgres'
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=${POSTGRES_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DATABASE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_DATABASE}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      - microservices

networks:
  microservices:
    driver: bridge